### ISSUE TITLE
Nested groups

### ISSUE THREAD

**Issue by iceberk** [hackley2/super-table#1]
Hello,

With this plugin, is it possible to create hierarchical table with more than 1 collapsible level?

**Comment by hackley2** [comment]
Hi, each collapsing group can have only 1 collapsible level. It can have multiple groups that collapse independently of each other, but the groups should not overlap. You can check out https://andrewhackley.com/super-table/demo for a full demo of how the collapsing row or column groups work. While it doesn't sound like this plugin is exactly what you're looking for, thanks for reaching out and hopefully that helps!
